pakerwreah/Calendr

- Calendr.xcodeproj/project.pbxproj
- Calendr/Main/MainViewController.swift
- Calendr/MenuBar/NextEventView.swift
> Fix next event blurring when losing focus

- Calendr/Events/EventDetailsViewController.swift
- Calendr/Main/MainViewController.swift
- Calendr/MenuBar/NextEventViewModel.swift
> Show next event details

- Calendr/Calendar/CalendarView.swift
- Calendr/Calendar/WeekNumberCellView.swift
> Small tweaks to the week numbers appearance

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/Icons.swift
- Calendr/Assets/Strings.generated.swift
- Calendr/Assets/en.lproj/Localizable.strings
- Calendr/Assets/es.lproj/Localizable.strings
- Calendr/Assets/fr.lproj/Localizable.strings
- Calendr/Assets/pt.lproj/Localizable.strings
- Calendr/Calendar/CalendarViewModel.swift
- Calendr/Calendar/DateSelector.swift
- Calendr/Events/EventDetailsViewController.swift
- Calendr/Events/EventDetailsViewModel.swift
- Calendr/Events/EventListViewModel.swift
- Calendr/Events/ReminderOptions.swift
- Calendr/Extensions/NSImage.swift
- Calendr/Main/AppDelegate.swift
- Calendr/Main/MainViewController.swift
- Calendr/MenuBar/StatusItemViewModel.swift
- Calendr/Providers/CalendarServiceProvider.swift
- Calendr/Settings/SettingsViewController.swift
- CalendrTests/EventDetailsViewModelTests.swift
- CalendrTests/Mocks/MockCalendarServiceProvider.swift
- CalendrTests/StatusItemViewModelTests.swift
> Add options to complete & reschedule reminders

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/Accessibility.swift
- Calendr/Assets/Icons.swift
- Calendr/Events/EventDetailsViewController.swift
- Calendr/Events/EventListView.swift
- Calendr/Extensions/NSStackView.swift
- Calendr/Main/MainViewController.swift
- Calendr/Settings/GeneralSettingsViewController.swift
- CalendrUITests/MainViewTests.swift
- CalendrUITests/UITestCase+Queries.swift
> Fix event details scroll 🔧

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/Accessibility.swift
- Calendr/Assets/Generated/Strings.generated.swift
- Calendr/Assets/de.lproj/Localizable.strings
- Calendr/Assets/en.lproj/Localizable.strings
- Calendr/Assets/es.lproj/Localizable.strings
- Calendr/Assets/fr.lproj/Localizable.strings
- Calendr/Assets/pt.lproj/Localizable.strings
- Calendr/Main/AppDelegate.swift
- Calendr/Main/MainViewController.swift
- Calendr/MenuBar/StatusItemViewModel.swift
- Calendr/Settings/GeneralSettingsViewController.swift
- Calendr/Settings/Prefs+UserDefaults.swift
- Calendr/Settings/SettingsViewModel.swift
- CalendrTests/Mocks/MockStatusItemSettings.swift
- CalendrTests/SettingsViewModelTests.swift
- CalendrTests/StatusItemViewModelTests.swift
- CalendrUITests/MainViewTests.swift
- CalendrUITests/SettingsTests.swift
- CalendrUITests/UITestCase+Queries.swift
> Add option to type a custom date format

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/Accessibility.swift
- Calendr/Assets/Generated/Strings.generated.swift
- Calendr/Assets/Icons.swift
- Calendr/Assets/de.lproj/Localizable.strings
- Calendr/Assets/en.lproj/Localizable.strings
- Calendr/Assets/es.lproj/Localizable.strings
- Calendr/Assets/fr.lproj/Localizable.strings
- Calendr/Assets/pt.lproj/Localizable.strings
- Calendr/Main/AppDelegate.swift
- Calendr/Main/MainViewController.swift
- Calendr/Main/MockMainViewController.swift
- Calendr/Previews/EventDetailsPreview.swift
- Calendr/Previews/EventListViewPreview.swift
- Calendr/Previews/EventViewPreview.swift
- Calendr/Providers/WorkspaceServiceProvider.swift
- Calendr/Settings/CalendarPickerViewController.swift
- Calendr/Settings/CalendarPickerViewModel.swift
- Calendr/Settings/SettingsViewController.swift
- CalendrTests/CalendarPickerViewModelTests.swift
- CalendrTests/EventViewModelLinkTests.swift
- CalendrTests/Mocks/MockWorkspaceServiceProvider.swift
- CalendrUITests/MainViewTests.swift
- CalendrUITests/UITestCase+Queries.swift
> Create new menu for settings and calendar picker

- Calendr.xcodeproj/project.pbxproj
- Calendr/Events/EventDetailsViewController.swift
The popover dismiss animation was a bit weird when we made the reminder disappear after selecting an action 🙃
> Disable reminder close animation for change action

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/Generated/Strings.generated.swift
- Calendr/Assets/de.lproj/Localizable.strings
- Calendr/Assets/en.lproj/Localizable.strings
- Calendr/Assets/es.lproj/Localizable.strings
- Calendr/Assets/fr.lproj/Localizable.strings
- Calendr/Assets/pt.lproj/Localizable.strings
- Calendr/Extensions/NSObject+Rx.swift
- Calendr/Main/AppDelegate.swift
- Calendr/Main/MainViewController.swift
- Calendr/Main/MockMainViewController.swift
- Calendr/Settings/AutoLauncher.swift
- Calendr/Settings/GeneralSettingsViewController.swift
- Calendr/Settings/SettingsViewModel.swift
- CalendrTests/SettingsViewModelTests.swift
> Add option to auto launch app in settings

- Calendr.xcodeproj/project.pbxproj
- Calendr/Events/EventDetails/EventDetailsViewModel.swift
- Calendr/Events/EventList/EventViewModel.swift
- Calendr/Events/EventUtils/EventUtils.swift
- Calendr/Mocks/Factories/EventModel+Factory.swift
- Calendr/Models/EventModel.swift
- Calendr/Previews/EventDetailsPreview.swift
- Calendr/Providers/CalendarServiceProvider.swift
- CalendrTests/EventDetailsViewModelTests.swift
- CalendrTests/EventViewModelTests.swift
> Show event time in local timezone

- Calendr.xcodeproj/project.pbxproj
- Calendr/Main/MainViewController.swift
- Calendr/MenuBar/StatusItemViewModel.swift
- CalendrTests/Mocks/MockCalendarServiceProvider.swift
- CalendrTests/NextEventViewModelTests.swift
- CalendrTests/StatusItemViewModelTests.swift
> Change menu bar icon when is someone's birthday

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/Generated/Strings.generated.swift
- Calendr/Assets/Icons.swift
- Calendr/Assets/de.lproj/Localizable.strings
- Calendr/Assets/en.lproj/Localizable.strings
- Calendr/Assets/es.lproj/Localizable.strings
- Calendr/Assets/fr.lproj/Localizable.strings
- Calendr/Assets/it.lproj/Localizable.strings
- Calendr/Assets/pt.lproj/Localizable.strings
- Calendr/Events/ContextMenu/ContextMenuFactory.swift
- Calendr/Events/ContextMenu/EventOptionsViewModel.swift
- Calendr/Events/ContextMenu/ReminderOptionsViewModel.swift
- Calendr/Events/EventDetails/EventDetailsViewModel.swift
- Calendr/Events/EventList/EventViewModel.swift
- Calendr/Extensions/NSGestureRecognizer+Rx.swift
- Calendr/Mocks/Factories/EventModel+Factory.swift
- Calendr/Models/EventModel.swift
- Calendr/Providers/CalendarServiceProvider.swift
- CalendrTests/ContextMenuFactoryTests.swift
- CalendrTests/EventOptionsViewModelTests.swift
- CalendrTests/ReminderOptionsViewModelTests.swift
Fixes #127 - memory leak in reactive gesture recognizer
> Add option to open event in the native Calendar app

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/zh-Hans.lproj/Localizable.strings
- Create Simplified Chinese localization
> Add Simplified Chinese localization

- Calendr/Assets/Accessibility.swift
- Calendr/Events/EventDetails/EventDetailsViewController.swift
- Calendr/Events/EventDetails/EventDetailsViewModel.swift
- Calendr/Main/MainViewController.swift
- Calendr/MenuBar/NextEventViewModel.swift
- CalendrTests/NextEventViewModelTests.swift
- CalendrUITests/MainViewTests.swift
- CalendrUITests/SettingsTests.swift
- CalendrUITests/UITestCase+Queries.swift
> Show both next event and reminder in the menu bar

- Calendr/Main/MainViewController.swift
- Calendr/MenuBar/StatusItemViewModel.swift
- Calendr/Previews/StatusItemPreview.swift
- CalendrTests/StatusItemViewModelTests.swift
> Support time in custom date format

- Calendr.xcodeproj/project.pbxproj
- Calendr/Config/Info.plist
- Calendr/Extensions/Error.swift
- Calendr/Providers/CalendarServiceProvider.swift
> Add new required permissions on macOS 14

- Calendr.xcodeproj/project.pbxproj
- Calendr.xcodeproj/xcshareddata/xcschemes/Calendr.xcscheme
- Calendr/Extensions/DateIntervalFormatter.swift
- Calendr/Main/MainViewController.swift
- Calendr/MenuBar/NextEventViewModel.swift
- Calendr/Settings/Prefs+UserDefaults.swift
- CalendrTests/NextEventViewModelTests.swift
> Hide empty next event in menu bar

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/Generated/Strings.generated.swift
- Calendr/Assets/Icons.swift
- Calendr/Assets/de.lproj/Localizable.strings
- Calendr/Assets/en.lproj/Localizable.strings
- Calendr/Assets/es.lproj/Localizable.strings
- Calendr/Assets/fr.lproj/Localizable.strings
- Calendr/Assets/it.lproj/Localizable.strings
- Calendr/Assets/pt.lproj/Localizable.strings
- Calendr/Assets/zh-Hans.lproj/Localizable.strings
- Calendr/Events/ContextMenu/ContextMenu.swift
- Calendr/Events/ContextMenu/ContextMenuFactory.swift
- Calendr/Events/ContextMenu/EventOptionsViewModel.swift
- Calendr/Events/ContextMenu/ReminderOptionsViewModel.swift
- Calendr/Events/EventDetails/EventDetailsViewController.swift
- Calendr/Events/EventDetails/EventDetailsViewModel.swift
- Calendr/Events/EventList/EventViewModel.swift
- Calendr/Main/MainViewController.swift
- Calendr/MenuBar/NextEventViewModel.swift
- CalendrTests/ContextMenuFactoryTests.swift
- CalendrTests/EventOptionsViewModelTests.swift
- CalendrTests/NextEventViewModelTests.swift
- CalendrTests/ReminderOptionsViewModelTests.swift
> Fix click in menu bar + ability to skip next event

- Calendr.xcodeproj/project.pbxproj
- Calendr.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Calendr/Main/Keyboard.swift
- Calendr/Main/MainViewController.swift
- Calendr/Settings/GeneralSettingsViewController.swift
> Add global shortcut recorder

- Calendr.xcodeproj/project.pbxproj
- Calendr/Main/AppDelegate.swift
- Calendr/Main/AppEditShortcuts.swift
- Calendr/Main/AppResignFocus.swift
> Fix desktop click not resigning focus

- Calendr.xcodeproj/project.pbxproj
- Calendr/Components/Popover.swift
> Fix wrong popover position in fullscreen

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/sv.lproj/Localizable.strings
> Swedish localization 🇸🇪

- Calendr.xcodeproj/project.pbxproj
- Calendr.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Calendr/Assets/Generated/Strings.generated.swift
- Calendr/Assets/Icons.swift
- Calendr/Assets/cs.lproj/Localizable.strings
- Calendr/Assets/de.lproj/Localizable.strings
- Calendr/Assets/en.lproj/Localizable.strings
- Calendr/Assets/es.lproj/Localizable.strings
- Calendr/Assets/fr.lproj/Localizable.strings
- Calendr/Assets/it.lproj/Localizable.strings
- Calendr/Assets/pt.lproj/Localizable.strings
- Calendr/Assets/sk.lproj/Localizable.strings
- Calendr/Assets/sv.lproj/Localizable.strings
- Calendr/Assets/zh-Hans.lproj/Localizable.strings
- Calendr/Components/Popover.swift
- Calendr/Extensions/NSMenu.swift
- Calendr/Extensions/Rx+Helpers.swift
- Calendr/Main/Keyboard.swift
- Calendr/Main/MainViewController.swift
- Calendr/Settings/GeneralSettingsViewController.swift
- Calendr/Settings/KeyboardViewController.swift
- Calendr/Settings/SettingsUI.swift
- Calendr/Settings/SettingsViewController.swift
> Create new shortcuts + new panel in settings

- Calendr.xcodeproj/project.pbxproj
- Calendr/Calendar/CalendarViewModel.swift
- Calendr/Main/AppDelegate.swift
- Calendr/Main/MainViewController.swift
- Calendr/Mocks/MockDateProvider.swift
- Calendr/Previews/CalendarViewPreview.swift
- Calendr/Providers/CalendarServiceProvider.swift
- Calendr/Providers/DateProvider.swift
- CalendrTests/CalendarViewModelTests.swift
- CalendrTests/Mocks/MockDateProvider.swift
> Fix week numbers when first weekday differs from macOS

- Calendr.xcodeproj/project.pbxproj
- Calendr/Main/AppDelegate.swift
- Calendr/Main/MockMainViewController.swift
- Calendr/Settings/Prefs+UserDefaults.swift
- Calendr/Settings/SettingsViewModel.swift
- CalendrTests/SettingsViewModelTests.swift
> Register default prefs in app delegate

- Calendr/Assets/it.lproj/Localizable.strings
> Update Localizable.strings for IT

- Calendr/Assets/sk.lproj/Localizable.strings
Translated the new tooltips strings
> Update Slovak translation

- Calendr/Assets/de.lproj/Localizable.strings
Sorry, blinded by upper and lower case letters, I forgot about this string 🙈.
> Update German translation

- Calendr.xcodeproj/project.pbxproj
- Calendr.xcodeproj/xcshareddata/xcschemes/Calendr.xcscheme
- Calendr/Assets/Strings.generated.swift
- Calendr/Assets/cs.lproj/Localizable.strings
- Calendr/Assets/de.lproj/Localizable.strings
- Calendr/Assets/en.lproj/Localizable.strings
- Calendr/Assets/es.lproj/Localizable.strings
- Calendr/Assets/fr.lproj/Localizable.strings
- Calendr/Assets/it.lproj/Localizable.strings
- Calendr/Assets/pt.lproj/Localizable.strings
- Calendr/Assets/sk.lproj/Localizable.strings
- Calendr/Assets/sv.lproj/Localizable.strings
- Calendr/Assets/zh-Hans.lproj/Localizable.strings
- Calendr/Assets/zh-Hant-TW.lproj/Localizable.strings
- Calendr/MenuBar/NextEventViewModel.swift
- Calendr/Mocks/MockNextEventSettings.swift
- Calendr/Previews/NextEventPreview.swift
- Calendr/Settings/GeneralSettingsViewController.swift
- Calendr/Settings/Prefs+UserDefaults.swift
- Calendr/Settings/SettingsViewModel.swift
- CalendrTests/Mocks/MockNextEventSettings.swift
- MISSING_TRANSLATIONS.md
> Add settings for flash/sound when event is close

- Calendr/Main/MockMainViewController.swift
- Calendr/Previews/CalendarPickerPreview.swift
- Calendr/Settings/CalendarPickerViewModel.swift
- Calendr/Settings/Prefs+UserDefaults.swift
- CalendrTests/CalendarPickerViewModelTests.swift
> New calendars enabled by default

- Calendr/Components/Popover.swift
- Calendr/Main/MainViewController.swift
> Convert popover into a non-activating panel

- Calendr/Events/EventDetails/EventDetailsViewController.swift
- Calendr/Events/EventDetails/EventDetailsViewModel.swift
- Calendr/Extensions/NSView.swift
- Calendr/Extensions/String.swift
> Notes meeting info section

- Calendr.xcodeproj/project.pbxproj
- Calendr/Calendar/CalendarViewModel.swift
- Calendr/Components/SearchSuggestionView.swift
- Calendr/Events/EventDetails/EventDetailsViewController.swift
- Calendr/Events/EventDetails/EventDetailsViewModel.swift
- Calendr/Extensions/NSControl+Rx.swift
- Calendr/Extensions/Rx+Helpers.swift
- Calendr/Main/MainViewController.swift
> Jump to date in search bar

- Calendr/Models/EventLink.swift
- CalendrTests/EventViewModelLinkTests.swift
> Show video button for webex meetings

- Calendr/Assets/it.lproj/Localizable.strings
> Update Localizable.strings (it)

- Calendr.xcodeproj/project.pbxproj
- Calendr/Events/EventList/EventView.swift
- Calendr/Events/EventList/EventViewModel.swift
- Calendr/Mocks/Factories/EventModel+Factory.swift
- Calendr/Models/EventModel.swift
- Calendr/Providers/CalendarServiceProvider.swift
> Show reminder priority

- Calendr.xcodeproj/project.pbxproj
- Calendr/Events/EventList/EventViewModel.swift
- CalendrTests/EventViewModelTests.swift
> Hide relative duration for all day reminders

- Calendr.xcodeproj/project.pbxproj
- Calendr/Components/Popover.swift
> Make sure popover closeAll is called on the main thread

- Calendr/Components/Popover.swift
> Fix popover window level

- Calendr.xcodeproj/project.pbxproj
- Calendr/Events/Background/EventBackground.swift
- Calendr/Events/EventList/EventView.swift
- Calendr/Events/EventList/EventViewModel.swift
- Calendr/MenuBar/NextEventViewModel.swift
- Calendr/Previews/EventViewPreview.swift
- Calendr/Previews/NextEventPreview.swift
- CalendrTests/EventViewModelProgressTests.swift
- CalendrTests/NextEventViewModelTests.swift
> Show next pending events

- Calendr.xcodeproj/project.pbxproj
- Calendr/Automation/CalendarScript.swift
> Fix popover not closing

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/ja.lproj/Localizable.strings
> Japanese Translation 🇯🇵

- Calendr/Events/EventDetails/EventDetailsViewController.swift
> Fix meeting info collapsing with big regular notes

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/ko.lproj/Localizable.strings
Add Korean translation support!
> Add Korean translation 🇰🇷

- CalendrTests/DateSearchParserTests.swift
I really have no clue what goes through Apple's mind regarding `NSDataDetector`.
> Fix date search parser unit tests

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/ru.lproj/Localizable.strings
- Calendr/Assets/tr.lproj
- Calendr/Assets/tr.lproj/Localizable.strings
> Add Turkish translation 🇹🇷

- Calendr/Assets/ru.lproj/Localizable.strings
Updated several Russian translations for better clarity and consistency. Adjusted terminology, grammar, and phrasing to align with standard usage and context within the app.
> Improve Russian translations

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/uk.lproj/Localizable.strings
Hello, I added Ukrainian localization to the project.
It's not Google translated, but properly translated by me.
> Add Ukrainian translation 🇺🇦

- .gitignore
- Calendr/Assets/uk.lproj/Localizable.strings
In `.gitignore` I added .DS_Store which is always trying to be staged in git, a bit annoying :)
> Update Ukrainian translation 🇺🇦 and gitignore

- Calendr/Assets/it.lproj/Localizable.strings
> Update italian translation 🇮🇹

- Calendr/Models/EventModel.swift
- Calendr/Providers/WorkspaceServiceProvider.swift
> Encode event id when opening system calendar

- Calendr.xcodeproj/project.pbxproj
- Calendr/Events/ContextMenu/ContextMenu.swift
- Calendr/Providers/CalendarServiceProvider.swift
> Finally fix the error saving recurrent events

- Calendr.xcodeproj/project.pbxproj
- Calendr.xcodeproj/xcshareddata/xcschemes/Calendr.xcscheme
- Calendr/Extensions/Collection.swift
- Calendr/Settings/GeneralSettingsViewController.swift
> Fix crash setting up date formatter in settings

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/Icons.swift
- Calendr/Main/MainViewController.swift
- Calendr/Mocks/MockAppearanceSettings.swift
- Calendr/Settings/AppearanceViewController.swift
- Calendr/Settings/Prefs+UserDefaults.swift
- Calendr/Settings/SettingsUI.swift
- Calendr/Settings/SettingsViewModel.swift
- Calendr/Utils/DisposableWrapper.swift
- CalendrTests/SettingsViewModelTests.swift
> Add light/dark mode settings

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/he.lproj/Localizable.strings
- Calendr/Components/Label.swift
- Calendr/Events/EventDetails/EventDetailsViewController.swift
- Calendr/Events/EventList/EventView.swift
Fixing `Label` default alignment from left to natural solves 99% of the alignment issues in RTL interfaces. There can be future improvements, but this is enough for now.
> Added hebrew localization & fixed alignment problems in RTL languages

- Calendr.xcodeproj/project.pbxproj
- Calendr/Calendar/CalendarCellViewModel.swift
- CalendrTests/CalendarViewModelTests.swift
> Hide completed reminder dots

- Calendr/Assets/sk.lproj/Localizable.strings
- MISSING_TRANSLATIONS.md
> Update Slovak translation 🇸🇰

- Calendr/Events/EventList/EventListView.swift
- Calendr/Events/EventList/EventView.swift
- Calendr/Main/MainViewController.swift
> Improve event progress indicator

- Calendr/Events/EventList/EventListViewModel.swift
- CalendrTests/EventListViewModelTests.swift
> Show relative time to upcoming event

- Calendr.xcodeproj/project.pbxproj
- Calendr/Events/EventDetails/EventDetailsViewController.swift
> Fix attachments layout with long names

- Calendr.xcodeproj/project.pbxproj
- Calendr/Assets/Strings.generated.swift
- Calendr/Assets/cs.lproj/Localizable.strings
- Calendr/Assets/de.lproj/Localizable.strings
- Calendr/Assets/el.lproj/Localizable.strings
- Calendr/Assets/en.lproj/Localizable.strings
- Calendr/Assets/es.lproj/Localizable.strings
- Calendr/Assets/fr.lproj/Localizable.strings
- Calendr/Assets/he.lproj/Localizable.strings
- Calendr/Assets/it.lproj/Localizable.strings
- Calendr/Assets/ja.lproj/Localizable.strings
- Calendr/Assets/ko.lproj/Localizable.strings
- Calendr/Assets/pt.lproj/Localizable.strings
- Calendr/Assets/ru.lproj/Localizable.strings
- Calendr/Assets/sk.lproj/Localizable.strings
- Calendr/Assets/sq.lproj/Localizable.strings
- Calendr/Assets/sv.lproj/Localizable.strings
- Calendr/Assets/tr.lproj/Localizable.strings
- Calendr/Assets/uk.lproj/Localizable.strings
- Calendr/Assets/zh-Hans.lproj/Localizable.strings
- Calendr/Assets/zh-Hant-TW.lproj/Localizable.strings
- Calendr/Components/TrackingView.swift
- Calendr/Main/MainViewController.swift
- Calendr/Main/StatusItemClickHandler.swift
- Calendr/Mocks/MockStatusItemSettings.swift
- Calendr/Settings/GeneralSettingsViewController.swift
- Calendr/Settings/Prefs+UserDefaults.swift
- Calendr/Settings/SettingsViewModel.swift
- CalendrTests/Mocks/MockStatusItemSettings.swift
- MISSING_TRANSLATIONS.md
> Add option to open calendar on menu bar hover

- Calendr/MenuBar/NextEventViewModel.swift
- Calendr/Settings/GeneralSettingsViewController.swift
- CalendrTests/NextEventViewModelTests.swift
> Increase next event fetch limit

- Calendr.xcodeproj/project.pbxproj
- Calendr.xcodeproj/xcshareddata/xcschemes/Calendr.xcscheme
- Calendr/Events/EventList/EventIntervalView.swift
- Calendr/Events/EventList/EventIntervalViewModel.swift
- Calendr/Events/EventList/EventListView.swift
- Calendr/Events/EventList/EventListViewModel.swift
- CalendrTests/EventListViewModelTests.swift
- CalendrTests/EventViewModelTests.swift
Small clean up + fix broken test on macOS 26
> Create event list interval view model

- Calendr/Assets/fr.lproj/Localizable.strings
- MISSING_TRANSLATIONS.md
Figured I could spend a few minutes updating a translation file. :)
> Update French translation 🇫🇷
